### PR TITLE
Bump version of u-root

### PR DESCRIPTION
**Pull request by rjoleary**
Signed-off-by: Ryan O'Leary <ryan@ryanoleary.ca>

### CODE REVIEW

**Comment by orangecms** [comment]
```
# github.com/u-root/u-root/pkg/cmdline
/go/pkg/mod/github.com/u-root/u-root@v0.9.0/pkg/cmdline/cmdline.go:66:14: undefined: io.ReadAll
note: module requires Go 1.17
FAIL	github.com/linuxboot/fiano/cmds/fmap [build failed]
```

This CI setup is using an old Go 1.13 and printing a deprecation message.

**Comment by orangecms** [comment]
https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034

so we can switch to cimg/go:1.17 or something, 1.19 has just been released

**Comment by rjoleary** [comment]
> https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034
> 
> so we can switch to cimg/go:1.17 or something, 1.19 has just been released

Thank you so much!

**Review by orangecms — APPROVED** [review]
🥳

**Pull request merged**
