### PR TITLE
Add RSAPSS and SHA384 support for key manifest generation

### PR DESCRIPTION
**Pull request by ChriMarMe**
Signed-off-by: Christopher Meis <christopher.meis@9elements.com>

### CODE REVIEW

**Review by xaionaro — APPROVED** [review]
Am I understand correctly RSAPSS was never working before?

**Comment by ChriMarMe** [comment]
Yes and not. Autodetection never worked with RSAPSS, because it just assumed: "Oh you have RSA key, then you go with RSASSA.

**Comment by ChriMarMe** [comment]
Before I merge, I need to make some tests. So leave the merging to me.

**Review by orangecms — APPROVED** [review]
LGTM :)

**Comment by orangecms** [comment]
> Before I merge, I need to make some tests. So leave the merging to me.

Oops, sorry, I missed this comment... 😅

**Comment by ChriMarMe** [comment]
My bad, shouldnt have made it PR and left it as Draft.

**Pull request merged**
