### PR TITLE
Add package "bytes"

### PR DESCRIPTION
**Pull request by rihter007**
The first step to move AMD package which relies on the Range structure

### CODE REVIEW

**Comment by rihter007** [comment]
Smth went wrong, extra files were added

**Comment by GanShun** [comment]
Can you rebase on master and try again?

**Comment by rihter007** [comment]
> Can you rebase on master and try again?

Done, sorry for delay.

**Comment by rihter007** [comment]
Will fix license and rewrite tests

**Review by xaionaro — APPROVED** [review]

**Pull request merged**
