### PR TITLE
intel/metadata: pretty print specific key manifests

### PR DESCRIPTION
**Pull request by orangecms**
This allows for better distinguishing them.

Note: I cannot get the manifest codegen to work in a Go module, so I manually made the changes as  I understand it. Someone please verify.

See also: https://github.com/xaionaro-go/gosrc/issues/1

### CODE REVIEW

**Comment by xaionaro** [comment]
> Note: I cannot get the manifest codegen to work in a Go module, so I manually made the changes as I understand it. Someone please verify.

@orangecms : Have you followed https://github.com/linuxboot/fiano/blob/main/pkg/intel/metadata/README.md ?

**Comment by xaionaro** [comment]
It looks like `manifestcodegen` is broken by https://github.com/linuxboot/fiano/pull/394

The way you could use it is:
```
cd `go env GOPATH`/src/github.com/linuxboot/fiano/pkg/intel/metadata/cbnt
git remote add orangecms https://github.com/orangecms/fiano
git checkout print-as-key-manifest
GO111MODULE=off go run ./../common/manifestcodegen/cmd/manifestcodegen/ . ./cbntbootpolicy ./cbntkey
```

But it currently does weird stuff like this:
```
-       "github.com/linuxboot/fiano/pkg/intel/metadata/cbnt"
+       "github.com/linuxboot/fiano/pkg/intel/metadata/TODO_PACKAGE"
        "github.com/linuxboot/fiano/pkg/intel/metadata/common/pretty"
```

I'll fix this :(

Also https://github.com/linuxboot/fiano/blob/main/pkg/intel/metadata/README.md wasn't updated after https://github.com/linuxboot/fiano/pull/394 .

**Review by xaionaro — APPROVED** [review]

**Comment by xaionaro** [comment]
Let's merge this PR as is, and the codegen I'll tackle soon.

**Comment by zaolin** [comment]
That might be a bug I introduced

**Pull request merged**
