### PR TITLE
circleci: go get -u ... -> go install ...@latest

### PR DESCRIPTION
**Pull request by rminnich**

### CODE REVIEW

**Comment by rminnich** [comment]
we need to remove golangci-lint usage. It's ignoring our go.mod version and flagging errors for newer go versions.

**Comment by rminnich** [comment]
another problem -- our tests no longer pass :-(

This project needs some work.

**Comment by rminnich** [comment]
I'm going to chump this in. It's fixing a CI problem.

**Comment by orangecms** [comment]
Yes, indeed, a good bunch of maintenance is necessary.

I'll be happy to help out.

**Pull request merged**
