### PR TITLE
Fuzz

### PR DESCRIPTION
**Pull request by rminnich**
This is mpictor's old fuzz stuff all cleaned up. 

We can squash these commits, but perhaps,  because fuzzing is a bit new, we should leave them as is. I don't know.

Maybe there's no instructive value to keeping the mess separate. 2020 was a long time ago.

### CODE REVIEW

**Comment by rminnich** [comment]
I think it's time to drop the golangci-lint test, it's just not a good thing to have in CI in my view.

**Comment by rminnich** [comment]
I'll probably squash these as well, given the random bits we don't want, like Gopkg.lock

**Review by binjip978 — APPROVED** [review]
I'm not sure about status of dvyukov/go-fuzz right now, it's half deprecated/alive.

**Comment by rminnich** [comment]
I'm going to push this in. From my looking at the fixes, they are legitimate, regardless of the state of the go-fuzz project. 

I've asked Dmitry for the status of go-fuzz.

**Comment by mpictor** [comment]
Thanks for taking care of this, I'd completely forgotten about that draft PR!

FWIW it shouldn't be too much trouble to rework the fuzz tests to use go's built-in fuzzing, though translating the corpus would probably be more work than it's worth.

**Pull request merged**
